#!/usr/bin/env bash
set -euo pipefail

PROJECT="${PROJECT:-/backup/taotao_work/sam_cell}"
NNUNET_PYTHON="${NNUNET_PYTHON:-/backup/taotao_work/venvs/nnunet/bin/python}"
REFINE_ROOT="${REFINE_ROOT:-$PROJECT/outputs/tissuenet_refine_combo_search_20260504}"
FULL_ROOT="${FULL_ROOT:-$PROJECT/experiments/cellcosmos_full_16777_20260503}"
RUN_SCRIPT="${RUN_SCRIPT:-$FULL_ROOT/run_full_samcell_tn_refine.sh}"
OUT_DIR="${OUT_DIR:-$FULL_ROOT/samcell_refine_final}"
SESSION_NAME="${SESSION_NAME:-full_samcell_refine_final}"
POLL_SECONDS="${POLL_SECONDS:-300}"
CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES:-0}"
export CUDA_VISIBLE_DEVICES

LOG_DIR="$FULL_ROOT/logs"
LOG="$LOG_DIR/ensure_samcell_refine_after_cellsam.log"
mkdir -p "$LOG_DIR"
exec > >(tee -a "$LOG") 2>&1

count_labels() {
  local dir="$1"
  local pattern="$2"
  if [ ! -d "$dir" ]; then
    echo 0
    return
  fi
  find "$dir" -maxdepth 1 -type f -name "$pattern" 2>/dev/null | wc -l | tr -d ' '
}

cd "$PROJECT"
date
echo "waiting for accepted refine decision: $REFINE_ROOT/decision.json"
while [ ! -s "$REFINE_ROOT/decision.json" ]; do
  sleep "$POLL_SECONDS"
done

ACCEPTED="$("$NNUNET_PYTHON" - <<PY
import json
from pathlib import Path
decision = json.loads(Path("$REFINE_ROOT/decision.json").read_text(encoding="utf-8"))
print("true" if decision.get("accepted") else "false")
PY
)"

if [ "$ACCEPTED" != "true" ]; then
  echo "refine was rejected; not starting $SESSION_NAME"
  date
  exit 0
fi

echo "waiting for run script generated by ensure_samcell_after_tn_refine: $RUN_SCRIPT"
while [ ! -s "$RUN_SCRIPT" ]; do
  sleep "$POLL_SECONDS"
done

if [ -s "$OUT_DIR/summary.csv" ]; then
  echo "refine full metrics already complete: $OUT_DIR/summary.csv"
  date
  exit 0
fi

while tmux has-session -t full_cellsam_prestart 2>/dev/null; do
  cellsam_labels="$(count_labels "$FULL_ROOT/cellsam_generalist/predictions/labels" "*_cellsam.tif")"
  echo "$(date '+%F %T %Z') full_cellsam_prestart is still running on GPU0; CellSAM labels=$cellsam_labels/16777; waiting before starting $SESSION_NAME on GPU0"
  sleep "$POLL_SECONDS"
done

if tmux has-session -t "$SESSION_NAME" 2>/dev/null; then
  echo "$SESSION_NAME already exists; not starting duplicate"
  date
  exit 0
fi

if [ -s "$OUT_DIR/summary.csv" ]; then
  echo "refine full metrics completed while waiting: $OUT_DIR/summary.csv"
  date
  exit 0
fi

tmux new-session -d -s "$SESSION_NAME" "CUDA_VISIBLE_DEVICES=$CUDA_VISIBLE_DEVICES bash '$RUN_SCRIPT'"
echo "started $SESSION_NAME on GPU$CUDA_VISIBLE_DEVICES after CellSAM session ended"
tmux ls | grep -E "$SESSION_NAME|full_samcell_final|full_cellsam_prestart" || true
date
